name: generate Documentation

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Give permission to run scripts
        run: chmod +x ./docs/scripts/doc8_style_check.sh

      - name: Install Dependencies
        working-directory: ./docs
        run:  pip install -r requirements.txt

      - name: Check Sphinx Documentation build minimally
        working-directory: ./docs
        run: sphinx-build -b linkcheck -EW source build

      - name: Check for documentation style errors
        working-directory: ./docs
        run: ./scripts/doc8_style_check.sh
