name: run tests

on: [push, pull_request]

env:
  DB_NAME: vulnerablecode
  DB_USER: vulnerablecode
  DB_PASSWORD: vulnerablecode

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make dev envfile

# Disable codestyle checks until we have cleaned up the code
#      - name: Validate code format
#        run: make check

      - name: Run tests
        run: make test
        env:
          GH_TOKEN: 1 
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          VULNERABLECODE_DB_NAME: ${{ env.DB_NAME }}
          VULNERABLECODE_DB_USER: ${{ env.DB_USER }}
          VULNERABLECODE_DB_PASSWORD: ${{ env.DB_PASSWORD }}
